<?php require VIEWS_PATH.'site/includes/header.phtml';?>

<div class="container">
    <h1>Product</h1>
    <hr>
    <div class="col-md-4">
        <img src="https://via.placeholder.com/150x150.png?text=<?=$this->product['name'];?>" alt="" class="img-responsive">
    </div>
    <div class="col-md-8">
        <h2><a href="<?=HOME;?>/product/<?=$this->product['id'];?>"><?=$this->product['name'];?></a></h2>
        <p><?=$this->product['description'];?></p>
        <p><?='R$ '.number_format($this->product['price'],2,',','.');?></p>    
    </div>
</div>

<?php require VIEWS_PATH.'site/includes/footer.phtml';?>